import type { GeminiEvent } from './types';

export const CANNED_EVENTS: GeminiEvent[] = [
  { eventDescription: "DEA raids a major port, seizing a huge shipment of Coke.", affectedItem: "Coke", priceModifier: 2.5, affectedCity: "Miami" },
  { eventDescription: "A new, potent strain of Weed hits the streets of Los Angeles.", affectedItem: "Weed", priceModifier: 0.6, affectedCity: "Los Angeles" },
  { eventDescription: "The mob cracks down on Heroin dealers in Chicago, creating a shortage.", affectedItem: "Heroin", priceModifier: 2.8, affectedCity: "Chicago" },
  { eventDescription: "A famous musician praises Acid in an interview, demand skyrockets in Las Vegas.", affectedItem: "Acid", priceModifier: 2.2, affectedCity: "Las Vegas" },
  { eventDescription: "A batch of cheap, low-quality Speed floods Houston.", affectedItem: "Speed", priceModifier: 0.4, affectedCity: "Houston" },
  { eventDescription: "Customs in New York gets a new K-9 unit, sniffing out Coke imports.", affectedItem: "Coke", priceModifier: 2.1, affectedCity: "New York" },
  { eventDescription: "A music festival in Boston causes a spike in demand for Weed.", affectedItem: "Weed", priceModifier: 1.8, affectedCity: "Boston" },
  { eventDescription: "Colombian cartels flood Bogotá with pure Coke, prices plummet.", affectedItem: "Coke", priceModifier: 0.25, affectedCity: "Bogotá" },
  { eventDescription: "A key Heroin supply line from Kabul is disrupted by conflict.", affectedItem: "Heroin", priceModifier: 2.9, affectedCity: "Kabul" },
  { eventDescription: "Dutch police bust a major Acid lab near Amsterdam.", affectedItem: "Acid", priceModifier: 2.5, affectedCity: "Amsterdam" },
  { eventDescription: "Border patrol in Erie gets lax, allowing cheap Weed to flow in.", affectedItem: "Weed", priceModifier: 0.7, affectedCity: "Erie" },
  { eventDescription: "A tech billionaire's tweet about microdosing causes an Acid craze in Los Angeles.", affectedItem: "Acid", priceModifier: 1.9, affectedCity: "Los Angeles" },
  { eventDescription: "A turf war in New York disrupts the Heroin trade.", affectedItem: "Heroin", priceModifier: 2.4, affectedCity: "New York" },
  { eventDescription: "A new smuggling route opens up, bringing cheap Speed to Miami.", affectedItem: "Speed", priceModifier: 0.5, affectedCity: "Miami" },
  { eventDescription: "An influential gang in Chicago starts pushing their own Weed, driving down prices.", affectedItem: "Weed", priceModifier: 0.65, affectedCity: "Chicago" },
  { eventDescription: "Celebrity overdose linked to fentanyl-laced Coke in Las Vegas scares buyers.", affectedItem: "Coke", priceModifier: 0.5, affectedCity: "Las Vegas" },
  { eventDescription: "A key chemical precursor for Speed becomes scarce in Amsterdam.", affectedItem: "Speed", priceModifier: 2.3, affectedCity: "Amsterdam" },
  { eventDescription: "Afghan poppy harvests are bountiful, Heroin is cheap in Kabul.", affectedItem: "Heroin", priceModifier: 0.2, affectedCity: "Kabul" },
  { eventDescription: "A peaceful protest in Boston turns into a party, everyone wants Weed.", affectedItem: "Weed", priceModifier: 1.7, affectedCity: "Boston" },
  { eventDescription: "A major bust in Houston makes Heroin hard to find.", affectedItem: "Heroin", priceModifier: 2.6, affectedCity: "Houston" },
  { eventDescription: "A documentary about the cartels glorifies the Coke trade, demand rises in Miami.", affectedItem: "Coke", priceModifier: 1.8, affectedCity: "Miami" },
  { eventDescription: "A superlab in the desert gets raided, Meth is scarce in Las Vegas.", affectedItem: "Meth", priceModifier: 2.7, affectedCity: "Las Vegas" },
  { eventDescription: "Bikers flood Houston with cheap Meth.", affectedItem: "Meth", priceModifier: 0.3, affectedCity: "Houston" },
  { eventDescription: "A politician's 'war on Meth' campaign in Erie backfires, driving up street prices.", affectedItem: "Meth", priceModifier: 2.0, affectedCity: "Erie" },
  { eventDescription: "A new synthesis method makes LSD cheap and plentiful in Amsterdam.", affectedItem: "LSD", priceModifier: 0.4, affectedCity: "Amsterdam" },
  { eventDescription: "A university study on psilocybin's benefits boosts Mushroom demand in Los Angeles.", affectedItem: "Mushrooms", priceModifier: 1.8, affectedCity: "Los Angeles" },
  { eventDescription: "A crackdown on poppy fields in Kabul creates an Opium shortage.", affectedItem: "Opium", priceModifier: 3.0, affectedCity: "Kabul" },
  { eventDescription: "The Bayou Boys successfully cultivate a potent new strain of Mushrooms in Houston.", affectedItem: "Mushrooms", priceModifier: 0.5, affectedCity: "Houston" },
  { eventDescription: "A 'Summer of Love' revival in Los Angeles skyrockets demand for LSD.", affectedItem: "LSD", priceModifier: 2.5, affectedCity: "Los Angeles" },
  { eventDescription: "A massive rave in Miami creates a huge demand for Ecstasy.", affectedItem: "Ecstasy", priceModifier: 2.2, affectedCity: "Miami" },
  { eventDescription: "A bad batch of PCP hits Chicago, scaring away buyers.", affectedItem: "PCP", priceModifier: 0.4, affectedCity: "Chicago" },
  { eventDescription: "DEA issues a national warning about Fentanyl, prices skyrocket due to scarcity.", affectedItem: "Fentanyl", priceModifier: 2.9, affectedCity: "New York" },
  { eventDescription: "A Dutch chemist floods Amsterdam with cheap, high-quality Ecstasy.", affectedItem: "Ecstasy", priceModifier: 0.3, affectedCity: "Amsterdam" }
];